name: Build and Generate PDF

# Triggers the workflow when a new commit is pushed to the repository
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: docker build --tag my_tag -f Dockerfile .

      - name: Generate PDF
        run: docker run -it my_tag /bin/bash
