name: Publish PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish PDF to Github
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: ./main.pdf
    - name: Pull
      run: |
        git config pull.rebase false
        git pull main resume
        
    - name: Push output file to resume branch
      uses: ad-m/github-push-action@master

      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: resume
        directory: ./
