name: Build and Publish PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --tag my_tag -f Dockerfile .

    - name: Generate PDF
      run: docker run my_tag /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"

    - name: Publish PDF to Github
      uses: actions/upload-artifact@v2
      with:
        name: output.pdf
        path: ./output.pdf

    - name: Push output file to pdf-output branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pdf-output
        directory: ./

