name: Publish PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish PDF to Github
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: ./main.pdf

    - name: Push output file to resume branch
      uses: ad-m/MariaMezentseva@master

      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: resume
        directory: ./
    - name: Download repository changes
      uses: actions/checkout@v2
      with:
        ref: resume
        fetch-depth: 0

    - name: Verify file changes
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q 'main.pdf'; then
          echo "File main.pdf changed. Committing changes..."
          git commit -m 'Updated main.pdf'
          git push
        else
          echo "File main.pdf did not change."
        fi

